services:
  postgres:
    image: postgres:latest
    container_name: todo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    volumes:
      - postgres_data:/var/lib/postgresql/todo

volumes:
  postgres_data: